name: sync-pr-to-feishu

on:
  schedule:
    - cron: "0 2/4 * * *"
  workflow_dispatch:

jobs:
  sync:
    if: github.repository_owner == 'labex-labs'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Sync to Feishu
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pip install requests
          python .github/scripts/sync-pr-to-feishu.py --appid "$APP_ID" --appsecret "$APP_SECRET" --ghtoken "$GH_TOKEN" --repo $GITHUB_REPOSITORY
          pip install jsonschema
          python .github/scripts/sync-labs-to-feishu.py --appid "$APP_ID" --appsecret "$APP_SECRET" --repo $GITHUB_REPOSITORY --schema .github/scripts/lab_schema.json